### ISSUE TITLE
Class 'PHPExcel_Settings' not found

### ISSUE THREAD

**Issue by jiansongjay** [kartik-v/yii2-export#103]
I didn't install yii2-export by composer. Just copy phpofice/PHPExcel and yii2-export to the vendor. When I run the exportMenu it shows warning that PHPExcel_Settings not found. Where should I set up except extentions.php before I run it.

**Comment by kartik-v** [comment]
Unfortunately cannot much help you here - since the module has several dependencies and recommend to install via composer. Though the error seems like your installed PHP Excel is not correct.


You may ask for programming tips and generic help queries in this [new Q&A forum](http://webtips.krajee.com/questions)
