### ISSUE TITLE
Not able to export file 

### ISSUE THREAD

**Issue by kakul232** [kartik-v/yii2-export#116]
The Export button is displayig but when i click the button . nothing happens  . no error in console and netwrk .

**Comment by kakul232** [comment]
Can you update Why its happening

**Comment by jsivakumaran** [comment]
Did you manage to figure it out @kakul232 ?  Because I am having the same issue and I've searched on yii2 forums and stack overflow and krajee and tried several different solutions but none seem to work.  Just can't download the files.  I can click on the menu and a popup will show up saying exporting but nothing will get downloaded.

**Comment by rizrob66** [comment]
I have the same problem in my grid, please help us.

**Comment by rizrob66** [comment]
I update to last version, and It works again. I hope it helps.
