### ISSUE TITLE
How can I export only the selected rows?

### ISSUE THREAD

**Issue by imRainChen** [kartik-v/yii2-export#122]
How can I export only the selected rows?  
I could not find any example for that. 
Thanks

**Comment by kartik-v** [comment]
It is not possible the way you are requesting and you may need to write your own code for this. This is because the extension entirely relies on the DATA you are providing from your yii dataProvider.

If you need selected rows OR filtered rows OR whatever... you need to send this filtered query data through your dataProvider to trigger the export for what you need.

**Comment by imRainChen** [comment]
Ok， thank for your help！
