### ISSUE TITLE
Page summary not showing in exported file

### ISSUE THREAD

**Issue by nazakar** [kartik-v/yii2-export#162]
I am using the export menu for export I am not getting the page summary. i have 'showPageSummary' => true, in ExportMenu and in GridView, and also 
[
           'attribute'=>'value',
    'pageSummary'=>true,
          ],  
Thanks

**Comment by mpavlin** [comment]
Same issue here, it is exported correctly in CVS or PDF, missing in Excel.

**Comment by kartik-v** [comment]
Page summary is not valid for `yii2-export` (because yii2-export by nature exports all rows). Page summary is only for `yii2-grid` where you have page wise data displayed. There will be a minor update to disable page summary validation for `yii2-export`. You can render the summary in `yii2-export` via the `footer` property for each column.
