### ISSUE TITLE
Cannot insert 0 value using content closure

### ISSUE THREAD

**Issue by deuxni** [kartik-v/yii2-export#188]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-export.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](https://demos.krajee.com/export) and [demos](https://demos.krajee.com/export-demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. use a closure to populate column values
2. given an attribute whose value is '01' in the model and you want insert 0 into Excel file 
3. you get '01' instead of 0

The issue origine is line 1474 into ExportMenu.php : the test "empty($value)"  made on the callback return prevent inserting 0 values.

**Comment by fsateler** [comment]
This is a more general issue. With the current code, any `FALSE` value will be overriden, since the check on [line 1474](https://github.com/kartik-v/yii2-export/blob/master/ExportMenu.php#L1474) uses `empty`, which returns true for valid values: `false`, `""`, `0`, `null`.

I'm not sure what the purpose of this check is. However, I think this check should be skipped at least when `getDataCellValue` is defined, since the raw value was already fetched in that case, and no guessing needs to be done.

@kartik-v , would you accept a PR removing the empty value check?

**Comment by fsateler** [comment]
FWIW, this causes problems when the `attribute` is not present in the model (like when adding properties for related models):

```php
[
    'attribute' => 'some_prop',
    'value' => 'related.some_prop',
],
```

**Comment by kartik-v** [comment]
Resolved via [updates to release v1.2.8](https://github.com/kartik-v/yii2-export/commit/68b5d48b3d36923b7d0065592ac65196db27bf40).

**Comment by fsateler** [comment]
@kartik-v The fix is still problematic, because `null` is a valid value to be returned by a value function, or a related property. If `ModelA` `HAS_ONE` `ModelB` , but the relation is optional, it would still cause issues because `attribute` might not exist in the `$model` object. Moreover, this ignores the case where the `value` function of a `DataColumn` explicitly returns null.

**Comment by kartik-v** [comment]
You need to return empty string instead of null in your model attribute values for your scenario. Usually null value is assumed as the variable not set.

**Comment by fsateler** [comment]
> You need to return empty string instead of null in your model attribute values for your scenario. Usually null value is assumed as the variable not set.

Well, but variable not set is a valid value to want to output to an excel file :). In particular, empty string is very much not the same as an unset cell.

Looking at the history of the file, the initial commit appears to have had `getValue($model, $column->attribute)` when it did not handle `DataColumn` https://github.com/kartik-v/yii2-export/commit/b05411b0ac3d6ce4292eb509047215c8bb9658b3#diff-a3b1d4975df133b74dc4a2a91f747608R567. However shortly after, support for that was added https://github.com/kartik-v/yii2-export/commit/a58d785e7e6d73176c956cda6f40612858dfdf8d#diff-76ff5c7d38933d45f929b811c29f3b62R691 . I think that if `getDataCellValue` is used, then `ExportMenu` should not try to guess the value, as the `DataColumn` already told us what the value should be, even if it is null.

**Comment by kartik-v** [comment]
Can you explain the issue - just needed to know if I am understanding correct?

You need to show in the excel export output a value which is NULL. Proposal is for you to show this as empty sting.

How different will an empty string data be from a NULL data in the output? Is it something else you feel that I am missing.

**Comment by fsateler** [comment]
The issue here is that the developer's choice of returning `null` in as the data value is not respected, and an attempt to obtain the attribute value is made. This has the following problems:

1. When the value being displayed is a computed value that may be null, this results in the wrong value being printed:

```php
[
    'attribute' => 'my_property',
    'value' => function ($m) { $m->property_enabled ? $m->my_property : null }, // this will print my_property even though I wanted to print null
]
```

2. When the value being displayed is a property of a related (but optional) model, this results in the wrong value being obtained:

```php
[
    'attribute' => 'related_id',
    'value' => 'related.name', // this will print related_id if related was not found
    'filter' => $all_relateds,
]
```

3. When the value being displayed is a property of a related, but optional model, and the attribute is only a property of the _filter_ model, this results in an error:

```php
[
    'attribute' => 'related_name',
    'value' => 'related.name', // Oops, this results in an exception because related_name does not exist in the result model
]
```


In practice, cases 1 and 2 are rare, and I have not yet encountered a failure. Case 3 I encountered yesterday.

**Comment by fsateler** [comment]
Hmm. looking at the code, I see that this issue is avoided if one does not set `enableFormatter = false`. Most formatters will return a nonempty string in almost every case.
