### ISSUE TITLE
I think this is a bug in ExportMenu.php line 739

### ISSUE THREAD

**Issue by mokeyjay** [kartik-v/yii2-export#190]
I set `stream` is `false`, it will export file to `@webroot/tmp`
but in views, download button href is like
"localhost/yii/web/index.php?r=tmp/xxx.xls", is 404
i think because i not enable `enablePrettyUrl` in `web/config.php`

so i set `linkPath` is `@web/tmp`, `stream` is `false` and remove **[** **]** from [line 739](https://github.com/kartik-v/yii2-export/blob/master/ExportMenu.php#L739)
it's work!

my english so bad, please don't mind :)

**Comment by kartik-v** [comment]
Note:

- `ExportMenu::folder` should point to the physical folder location
- `linkPath` must be an URL link

**Comment by ianfish** [comment]
Hey, you closed this issue but the bug is still there!
File ExportMenu.php, line 804:

`'href' => Url::to([self::slash($this->linkPath, '/') . $fileName])`

$this->linkPath is a string, but it's turned into an array. This way Url::to() interprets it as a route.
So, if I set linkPath to '@web/tmp', the resulting URL will be something like:
http://www.example.com/index.php?r=tmp/filename.xlsx

Maybe it would work OK if I had enabled pretty urls, but I didn't, so the best solution is still to strip those square brackets, like this:

`'href' => Url::to(self::slash($this->linkPath, '/') . $fileName)`

Great extension anyway, thank you very much!
