### ISSUE TITLE
Sanitize file names in a better way

### ISSUE THREAD

**Issue by lubobill1990** [kartik-v/yii2-export#330]
https://github.com/kartik-v/yii2-export/blob/29fc213889ad805f5e8f5574404c5341726343e9/src/ExportMenu.php#L802
Hi @kartik-v ,

If I don't specify the filename, using the default translation, there will be a php notice: iconv(): Detected an illegal character in input string

<img width="766" alt="image" src="https://user-images.githubusercontent.com/641540/91862781-f9e9e800-eca0-11ea-9ee5-2b0b3a7d0d18.png">

Besides, may I ask why iconv from UTF-8 to ISO-8859-1//TRANSLIT is needed here?

**Comment by Mohsen6558** [comment]
on Persian language too
I change code to:
        $filename = iconv("UTF-8", "ISO-8859-1//TRANSLIT", utf8_encode($this->filename));
from 
        $filename = iconv("UTF-8", "ISO-8859-1//TRANSLIT", $this->filename);

**Comment by kartik-v** [comment]
The reason `iconv` exists is because PHP Spreadsheet does not accept weird characters in filename. You need to supply the utf8 encoded filename as parameter to yii2-export if you are providing non Ascii characters.

@Mohsen6558 - you should not change the procedure - but do this at your input level. Maybe I will check if I can provide an enhancement to allow developers to choose this option.

**Comment by kartik-v** [comment]
Resolved via above commit.

**Comment by kartik-v** [comment]
Resolved via above commit.

**Comment by kartik-v** [comment]
Resolved via above commit.
