### ISSUE TITLE
How can I add text before header in report?

### ISSUE THREAD

**Issue by DenisOgr** [kartik-v/yii2-export#53]
I want to add some text before column and data.
I need shift report to second row and add some text.
I can not to do it, because _beginRow is private property (I can not expand this class and create getter to this property).
Why have you created private properties (why not protected)? 
Maybe can you add some property in widget, with text before  data in report?

**Comment by kartik-v** [comment]
> Why have you created private properties (why not protected)? 
Because its my choice on how I want my extension to be designed.

> I need shift report to second row and add some text. I can not to do it, because _beginRow is private property
You are using a wrong property to achieve your requirement. Read docs. Use the various events properties like `onInitWriter`, `onInitSheet`, `onRenderHeaderCell`, `onRenderDataCell`, `onRenderFooterCell`, `onRenderSheet` to use PHP Excel methods to modify output data.
