### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by smiffsoft** [kartik-v/yii2-export#82]
This uses lots of RAM. I've a table with around 37000 rows, the CSV exported from PhpMyAdmin is around 2MB in size.  Even giving 512MB to PHP in php.ini doesn't help export using this widget. Is there any way of exporting this many rows without allocating an enormous amount of RAM?

**Comment by kartik-v** [comment]
Note that as mentioned in docs, this extension depends on and uses the [PHP Excel library](https://phpexcel.codeplex.com/) to export. So you would need to read about various settings that would optimize the usage of the library.

However, for large volumes of data - its better to directly read / write via queries from the Database rather than use an intermediate PHP library like PHP Excel
